//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntershipsZ7.MyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResult", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IntershipsZ7.MyService.ListSOROfImmoInfoN5x5yyRL))]
    public partial class ServiceOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EssenceSOROfImmovablesz2cTNpOZ", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    public partial class EssenceSOROfImmovablesz2cTNpOZ : IntershipsZ7.MyService.ServiceOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntershipsZ7.MyService.Immovables EssenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntershipsZ7.MyService.Immovables Essence {
            get {
                return this.EssenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EssenceField, value) != true)) {
                    this.EssenceField = value;
                    this.RaisePropertyChanged("Essence");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListSOROfImmoInfoN5x5yyRL", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    public partial class ListSOROfImmoInfoN5x5yyRL : IntershipsZ7.MyService.ServiceOperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntershipsZ7.MyService.ImmoInfo[] ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntershipsZ7.MyService.ImmoInfo[] List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImmoInfo", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    public partial struct ImmoInfo : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Immovables", Namespace="http://schemas.datacontract.org/2004/07/CommonLib.Models")]
    [System.SerializableAttribute()]
    public partial class Immovables : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssigmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FootageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumbFloorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumbRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SizePlotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeApartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assigment {
            get {
                return this.AssigmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AssigmentField, value) != true)) {
                    this.AssigmentField = value;
                    this.RaisePropertyChanged("Assigment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Footage {
            get {
                return this.FootageField;
            }
            set {
                if ((this.FootageField.Equals(value) != true)) {
                    this.FootageField = value;
                    this.RaisePropertyChanged("Footage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumbFloors {
            get {
                return this.NumbFloorsField;
            }
            set {
                if ((this.NumbFloorsField.Equals(value) != true)) {
                    this.NumbFloorsField = value;
                    this.RaisePropertyChanged("NumbFloors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumbRooms {
            get {
                return this.NumbRoomsField;
            }
            set {
                if ((this.NumbRoomsField.Equals(value) != true)) {
                    this.NumbRoomsField = value;
                    this.RaisePropertyChanged("NumbRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SizePlot {
            get {
                return this.SizePlotField;
            }
            set {
                if ((this.SizePlotField.Equals(value) != true)) {
                    this.SizePlotField = value;
                    this.RaisePropertyChanged("SizePlot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeApart {
            get {
                return this.TypeApartField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeApartField, value) != true)) {
                    this.TypeApartField = value;
                    this.RaisePropertyChanged("TypeApart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetListOfNames", ReplyAction="http://tempuri.org/IService/GetListOfNamesResponse")]
        IntershipsZ7.MyService.ListSOROfImmoInfoN5x5yyRL GetListOfNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetListOfNames", ReplyAction="http://tempuri.org/IService/GetListOfNamesResponse")]
        System.Threading.Tasks.Task<IntershipsZ7.MyService.ListSOROfImmoInfoN5x5yyRL> GetListOfNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DBSave", ReplyAction="http://tempuri.org/IService/DBSaveResponse")]
        IntershipsZ7.MyService.ServiceOperationResult DBSave();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DBSave", ReplyAction="http://tempuri.org/IService/DBSaveResponse")]
        System.Threading.Tasks.Task<IntershipsZ7.MyService.ServiceOperationResult> DBSaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartImmovablesEdit", ReplyAction="http://tempuri.org/IService/StartImmovablesEditResponse")]
        IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ StartImmovablesEdit(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartImmovablesEdit", ReplyAction="http://tempuri.org/IService/StartImmovablesEditResponse")]
        System.Threading.Tasks.Task<IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ> StartImmovablesEditAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetImmovablesFieldValue", ReplyAction="http://tempuri.org/IService/SetImmovablesFieldValueResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IntershipsZ7.MyService.Immovables))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IntershipsZ7.MyService.ListSOROfImmoInfoN5x5yyRL))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IntershipsZ7.MyService.ServiceOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IntershipsZ7.MyService.ImmoInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IntershipsZ7.MyService.ImmoInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ))]
        IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ SetImmovablesFieldValue(string fieldName, object val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetImmovablesFieldValue", ReplyAction="http://tempuri.org/IService/SetImmovablesFieldValueResponse")]
        System.Threading.Tasks.Task<IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ> SetImmovablesFieldValueAsync(string fieldName, object val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelEdit", ReplyAction="http://tempuri.org/IService/CancelEditResponse")]
        IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ CancelEdit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelEdit", ReplyAction="http://tempuri.org/IService/CancelEditResponse")]
        System.Threading.Tasks.Task<IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ> CancelEditAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : IntershipsZ7.MyService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<IntershipsZ7.MyService.IService>, IntershipsZ7.MyService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IntershipsZ7.MyService.ListSOROfImmoInfoN5x5yyRL GetListOfNames() {
            return base.Channel.GetListOfNames();
        }
        
        public System.Threading.Tasks.Task<IntershipsZ7.MyService.ListSOROfImmoInfoN5x5yyRL> GetListOfNamesAsync() {
            return base.Channel.GetListOfNamesAsync();
        }
        
        public IntershipsZ7.MyService.ServiceOperationResult DBSave() {
            return base.Channel.DBSave();
        }
        
        public System.Threading.Tasks.Task<IntershipsZ7.MyService.ServiceOperationResult> DBSaveAsync() {
            return base.Channel.DBSaveAsync();
        }
        
        public IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ StartImmovablesEdit(int id) {
            return base.Channel.StartImmovablesEdit(id);
        }
        
        public System.Threading.Tasks.Task<IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ> StartImmovablesEditAsync(int id) {
            return base.Channel.StartImmovablesEditAsync(id);
        }
        
        public IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ SetImmovablesFieldValue(string fieldName, object val) {
            return base.Channel.SetImmovablesFieldValue(fieldName, val);
        }
        
        public System.Threading.Tasks.Task<IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ> SetImmovablesFieldValueAsync(string fieldName, object val) {
            return base.Channel.SetImmovablesFieldValueAsync(fieldName, val);
        }
        
        public IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ CancelEdit() {
            return base.Channel.CancelEdit();
        }
        
        public System.Threading.Tasks.Task<IntershipsZ7.MyService.EssenceSOROfImmovablesz2cTNpOZ> CancelEditAsync() {
            return base.Channel.CancelEditAsync();
        }
    }
}
