//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntershipsZ7.RemoteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResult", Namespace="http://schemas.datacontract.org/2004/07/SampleService")]
    [System.SerializableAttribute()]
    public partial class ServiceOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteService.ISaver")]
    public interface ISaver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaver/DBSave", ReplyAction="http://tempuri.org/ISaver/DBSaveResponse")]
        IntershipsZ7.RemoteService.ServiceOperationResult DBSave(CommonLib.Models.Immovables im);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaver/DBSave", ReplyAction="http://tempuri.org/ISaver/DBSaveResponse")]
        System.Threading.Tasks.Task<IntershipsZ7.RemoteService.ServiceOperationResult> DBSaveAsync(CommonLib.Models.Immovables im);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaverChannel : IntershipsZ7.RemoteService.ISaver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaverClient : System.ServiceModel.ClientBase<IntershipsZ7.RemoteService.ISaver>, IntershipsZ7.RemoteService.ISaver {
        
        public SaverClient() {
        }
        
        public SaverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IntershipsZ7.RemoteService.ServiceOperationResult DBSave(CommonLib.Models.Immovables im) {
            return base.Channel.DBSave(im);
        }
        
        public System.Threading.Tasks.Task<IntershipsZ7.RemoteService.ServiceOperationResult> DBSaveAsync(CommonLib.Models.Immovables im) {
            return base.Channel.DBSaveAsync(im);
        }
    }
}
